### ISSUE TITLE
I would like to add the solution for "N Queen" Problem

### ISSUE THREAD

**Issue by Visha17** [d-coder111/DSAmplify#136]
The N Queen is the problem of placing N chess queens on an N×N chessboard so that no two queens attack each other.

Pls assign this issue @d-coder111

**Comment by swarupsahu08** [comment]
hey @d-coder111 ,Can you assign me this issue

**Comment by Vikas3100** [comment]
hey maintainer @d-coder111 
I would like to work on this issue
could you please assign me this
