### ISSUE TITLE
i Would like to add Leetcode DSA Problem Solution 

### ISSUE THREAD

**Issue by UdaySharmaGitHub** [d-coder111/DSAmplify#140]
- i Would like to add Leetcode Problem Solution 
- with different Approaches and Different Time and Space Complexities
- Please assign @d-coder111 me this issue under Hacktofest or Hacktofest2024

**Comment by d-coder111** [comment]
Do add them but not in a separate folder..I mean add them by program name but don't create a separate folder for the same

**Comment by UdaySharmaGitHub** [comment]
@d-coder111  the Solutions is in C++ so, can i create a folder name leetcode solution inside of C++ folder?

**Comment by UdaySharmaGitHub** [comment]
ok, I'll add the leetcode solution folder which is categorized in EASY, MEDIUM and HARD .
Add it into the main C++ folder .
 Its work?

**Comment by d-coder111** [comment]
Add them by naming a programs differently..don't add leetcode folder.

**Comment by UdaySharmaGitHub** [comment]
ok
