### ISSUE TITLE
Need someone to automate the task of checking duplicates file when a new contributor contributes

### ISSUE THREAD

**Issue by d-coder111** [d-coder111/DSAmplify#15]

**Comment by HenrikTennebekk** [comment]
There should probably also be some structure to make it easier to find the different algorithms. Some directories or something. What do you think?

**Comment by d-coder111** [comment]
> There should probably also be some structure to make it easier to find the different algorithms. Some directories or something. What do you think?

Well I have thought of a website and raised the issue for the same..and looking contributors for the same.. Do you have better suggestions?

**Comment by FaizanAnwar01** [comment]
Hey @d-coder111, I'm interested in this issue, can you assign this issue to me.?
