### ISSUE TITLE
Build a better Homepage 

### ISSUE THREAD

**Issue by baranwalayush** [d-coder111/DSAmplify#154]
Hey @d-coder111,

I have really cool ideas to make the website functional by connecting it to the solutions provided by the people in all the languages.
<ol>
<li> I need to build a better homepage where the user can select language and based on the language we will show him/her the list of questions for which the solution is available
<li> When the user selects a certain problem, we will show him/her the solution of that question.
<li> I will be using flask library for the backend.
</ol>
 
I will work on the functionalities one by one. As of now, Please assign me this issue to better the homepage and project structure and if possible assign it under the hacktobefest label.

**Comment by d-coder111** [comment]
Hey @baranwalayush, we’d love to have your contributions! 👍😊 If you're seeking a 🎃Hacktoberfest-eligible repository to contribute to, feel free to check out this one: https://github.com/d-coder111/SpectrumOfPython.It's an absolute beginner-friendly repo. Don’t forget to star the repo to show your support✨, and we look forward to as many contributions as you can share! Keep coding...keep learning 💻🚀

**Comment by baranwalayush** [comment]
Thank U for assigning me this issue, I have opened a pull request.

**Comment by baranwalayush** [comment]
Thank you for merging.
