### ISSUE TITLE
Add functionality to connect the solutions of the DSA questions to the website

### ISSUE THREAD

**Issue by baranwalayush** [d-coder111/DSAmplify#156]
Hey @d-coder111,
As, I have mentioned in earlier issue that I can help in making this website functional. So, here is the plan -
<ul>
<li> Use flask in backend to connect the solutions provided by the various contributors with the website.
<li> Based on the selected language, we will show the users list of questions of which the solution is available.
</ul>

As of now I will be working on this issue. After this, we can add the functionality so that the user can click on particular question to see the answers. Please assign me this issue, and if possible under hacktoberfest label.

**Comment by baranwalayush** [comment]
Should I add proper comments, or let it be without comments?
And please add hacktoberfest label

**Comment by d-coder111** [comment]
Do add proper comments,any valid contributions are welcomed✨👍.

**Comment by baranwalayush** [comment]
Hey @d-coder111,
I believe now the website is functional and the solutions are well connected with it.
You should ask for someone who can make the website look more beautiful with a better frontend. And one suggestion that you should specify contributors to follow a specific file naming pattern for the solutions like _maximum_subarray_sum.cpp_ for a question of maximumSubarraySum. So that the question name can be fetched using the file name only, as done in the _app.py_ file.

And thanks for merging my PRs. I would love to keep contributing to this repository in the future too.

**Comment by d-coder111** [comment]
Honestly, loved your contributions and you are most welcome to suggest better ideas and contribute to it ❤😊.We appreciate any valuable contributions! 🚀✌...happy learning..happy coding. 
If you're interested in Python, take a look at this repo: https://github.com/d-coder111/SpectrumOfPython. It’s also accepted for Hacktoberfest, and we’d love to have you contribute!
