### ISSUE TITLE
Adding programs implementing data structures concepts and algorithms 

### ISSUE THREAD

**Issue by d-coder111** [d-coder111/DSAmplify#6]

**Comment by resilient-maximus** [comment]
Please assign me this issue

**Comment by d-coder111** [comment]
> Please assign me this issue

You can create a valid pr tagging this issue..if it seems fine i will merge ur pr

**Comment by resilient-maximus** [comment]
> _No description provided._



> description

https://github.com/d-coder111/DS-Learn-website/pull/13

**Comment by Adidem23** [comment]
@d-coder111 Bhaiya I want to add some Algorihtms realted to AI in the Java Directory

**Comment by d-coder111** [comment]
> @d-coder111 Bhaiya I want to add some Algorihtms realted to AI in the Java Directory

If it's in java language, do add in the folder by creating a pull request.
If it's in python create a new folder,I will add and make changes in my description.

**Comment by Adidem23** [comment]
it is java @d-coder111  bhaiya so i will add them in java folder

**Comment by d-coder111** [comment]
> it is java @d-coder111 bhaiya so i will add them in java folder

Do create a pull request, after reviewing it, I will merge it.

**Comment by Adidem23** [comment]
Yeah

**Comment by Thanush19** [comment]
added counting sort in java , kindly review my PR @d-coder111

**Comment by Thanush19** [comment]
add Given a [Perfect Binary Tree]( reverse the alternate level nodes of the binary tree in java. @d-coder111  review the PR

**Comment by Akshada-26** [comment]
Please merge my PR

**Comment by shubhalgupta** [comment]
@d-coder111 is this issue still open?

**Comment by d-coder111** [comment]
> @d-coder111 is this issue still open?

yes.
