### ISSUE TITLE
Create website table format showing program+contributors of this repository

### ISSUE THREAD

**Issue by d-coder111** [d-coder111/DSAmplify#8]

**Comment by SWAYAMKHANDURI** [comment]
Hey there I would like to work on this issue could you assign me the issue

**Comment by d-coder111** [comment]
> Hey there I would like to work on this issue could you assign me the issue

Sure..go ahead👍..good luck✌

**Comment by SWAYAMKHANDURI** [comment]
@d-coder111 You a HTML file right in where table is created right ?

**Comment by d-coder111** [comment]
> @d-coder111 You want a HTML file right in where table is created right ?

yes using html,css and javascrpit  ...like a full working website.. will deploy it later..but first like a table format something like...
Sr No  |  Name of the program | Contributor | Contributor's image

And it should add contributors automatically when they contribute on this repo

**Comment by d-coder111** [comment]
> > @d-coder111 You want a HTML file right in where table is created right ?
> 
> yes using html,css and javascrpit ...like a full working website.. will deploy it later..but first like a table format something like... Sr No | Name of the program | Contributor | Contributor's image
> 
> And it should add contributors automatically when they contribute on this repo

It's just basic frame..but you are free to style it and add more things

**Comment by SWAYAMKHANDURI** [comment]
alright it's gonna take some time but will surely do it by today itself

**Comment by d-coder111** [comment]
> alright it's gonna take some time but will surely do it by today itself

That's Great..Good luck🚀👍😊

**Comment by SWAYAMKHANDURI** [comment]
Hey there @d-coder111 , was busy in a hackathon from past few days will surely start working fast on this, apologies for so much delay

**Comment by d-coder111** [comment]
> Hey there @d-coder111 , was busy in a hackathon from past few days will surely start working fast on this, apologies for so much delay

No problem..not that big issue

**Comment by SWAYAMKHANDURI** [comment]
Hey there I have made a PR against this issue you can review the code and revert back for any changes if needed I am open to resolve them anytime

**Comment by d-coder111** [comment]
> Hey there I have made a PR against this issue you can review the code and revert back for any changes if needed I am open to resolve them anytime

Hey @SWAYAMKHANDURI ,
it is not working from my end and it would be great if it can be deployed. However i am still merging it and you can raise more pull requests for further improvement.

**Comment by d-coder111** [comment]
Hey @SWAYAMKHANDURI , do let me know if u are willing to do the required changes because our aim is to make a working website.

**Comment by d-coder111** [comment]
> Hey there I have made a PR against this issue you can review the code and revert back for any changes if needed I am open to resolve them anytime

Hey @SWAYAMKHANDURI ,
Any update?

**Comment by SWAYAMKHANDURI** [comment]
@d-coder111 for sure I can work on this but it might take some time cuz I am currently busy in other events also but will try my best on it 
Also regarding the not working part you'll have to install npm module for octokit on your system

**Comment by d-coder111** [comment]
> @d-coder111 for sure I can work on this but it might take some time cuz I am currently busy in other events also but will try my best on it Also regarding the not working part you'll have to install npm module for octokit on your system

Ok no problem👍..raise the pr whenever you complete the task as this is one of the most important part of the project.

**Comment by DhruvSeth18** [comment]
Can I work on this ?

**Comment by d-coder111** [comment]
> Can I work on this ?

Yeah sure, Go ahead ..good luck😊👍.

**Comment by DhruvSeth18** [comment]
just changing the css for now.

**Comment by SWAYAMKHANDURI** [comment]
@DhruvSeth18  we can work together on this project if you are willing to 😊

**Comment by DhruvSeth18** [comment]
yes bro 

just changed some CSS for now
![contributor's page](https://github.com/d-coder111/DSAmplify/assets/122422292/84845882-4040-4d09-b618-c59f7e0dfc8f)

**Comment by d-coder111** [comment]
> just changing the css for now. can i do so ?

Sure, In fact if you want to add some logo and make a creative design..you are most welcome and add DSAmplify website name..whatever creative you can make out of it😀✌.

**Comment by DhruvSeth18** [comment]
ok bro 😀

**Comment by AbdullahIshtiaqq** [comment]
Hey @d-coder111 , I would like to contribute to this issue if you could assign me. Will create a responsive react app, can be easily deployed on vercel, using react.js and material ui for attractive user interface.

**Comment by d-coder111** [comment]
You guys @SWAYAMKHANDURI  @DhruvSeth18 @AbdullahIshtiaqq  can work collaboratively🤝😊. Do let me know if you need some channel(may be discord) sort of thing for better communication and to exchange ideas. Good luck guys✌👍.

**Comment by DhruvSeth18** [comment]
can I push css change for now ?

**Comment by d-coder111** [comment]
> can I push css change for now ?

yeah sure..u are welcome to contribute more✌😊.

**Comment by DhruvSeth18** [comment]
@d-coder111  is the script.js working. with html file ?

**Comment by DhruvSeth18** [comment]
@d-coder111 added some code and modify css , trying new methods
for now I created a PR with this change 
1. created a new js file.
2. try github fetch query
3. modify css 

temporary this look like :- 

![dsaAmplifyPicture](https://github.com/d-coder111/DSAmplify/assets/122422292/d52bc50a-0e70-4f8c-b5a5-1bac981ce6f3)

**Comment by DhruvSeth18** [comment]
please merge my PR #78

**Comment by DhruvSeth18** [comment]
previous js file is not deleted

**Comment by d-coder111** [comment]
> @d-coder111 added some code and modify css , trying new methods for now I created a PR with this change
> 
> 1. created a new js file.
> 2. try github fetch query
> 3. modify css
> 
> temporary this look like :-
> 
> ![dsaAmplifyPicture](https://user-images.githubusercontent.com/122422292/277052323-d52bc50a-0e70-4f8c-b5a5-1bac981ce6f3.png)

Looks cool✌😊..You are welcome to include additional pages and attempt deployment, as having a functioning website would be truly fantastic.

**Comment by d-coder111** [comment]
Hey, any update ?

**Comment by DhruvSeth18** [comment]
Exam today

**Comment by DhruvSeth18** [comment]
Working on some other changes

**Comment by d-coder111** [comment]
> Exam today

Ok no problem.. Raise a pr whenever you feel like adding things.. Good luck 👍✌.
