### ISSUE TITLE
I want to add Algorithms in JAVA related to linked list.

### ISSUE THREAD

**Issue by sohamt-21** [d-coder111/DSAmplify#87]
1) Floyd's method of slow and fast pointers.
2) Cycle detection using this method.
3) After this cycle detection how to find the length of the cycle.
4) How to find the start of cycle.

**Comment by d-coder111** [comment]
Go ahead👍.. Good luck.. If they seem valid programs I will definitely merge them.

**Comment by d-coder111** [comment]
Kindly avoid redundant and duplicate programs before adding new programs.

**Comment by sohamt-21** [comment]
@d-coder111 I mistakenly added Cycle Start Node Finding algorithm along with LengthFinding of java. Can you please delete the CycleStartNodeSearch.java and i'll make another request.

**Comment by d-coder111** [comment]
okk
