### ISSUE TITLE
Add GCD finding using normal methods and using optimised Euclid's division rule  in JAVA.

### ISSUE THREAD

**Issue by sohamt-21** [d-coder111/DSAmplify#90]
I want to add a GCD finding algorithm which can be used frequently in number theory problems. It will have two approach one will be recursion and second will be Euclid's division Lemma with explanation of how it works in JAVA.

**Comment by d-coder111** [comment]
You don't have to create a issue for different programs..if it's related to the website of this project you can create a issue but for programs..directly raise a pr and if it seems valid i will add them.

**Comment by sohamt-21** [comment]
Okay ! Thank You
